---
name: Pull Request

"on":
  pull_request:

permissions:
  contents: read

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v6.0.3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.313.0
        with:
          ruby-version: "3.4.10"

      - name: Install ShellCheck
        run: |
          sudo apt-get update
          sudo apt-get install --yes shellcheck

      - name: Install actionlint
        run: |
          go install github.com/rhysd/actionlint/cmd/actionlint@v1.7.12
          echo "${HOME}/go/bin" >> "${GITHUB_PATH}"

      - name: Run checks
        run: bash script/check
